<a href="https://colab.research.google.com/github/faneza31nur/Natural-Language-Processing-NLP-/blob/main/LK_Faneza_Nur_Mardania_T5_Klasifikasi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

df = pd.read_csv('/content/drive/MyDrive/Data Analis Angkatan 2 Tahun 2026_Faneza Nur Mardania/21 Agustus 2026_Pertemuan 26/File Tugas/data_preprocessed.csv')
df = df.dropna(subset=['teks_processed', 'sentimen'])

X = df['teks_processed']
y = df['sentimen']

# Split SEBELUM vektorisasi (penting!)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

tfidf = TfidfVectorizer(max_features=500)
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf  = tfidf.transform(X_test)

print('Shape train:', X_train_tfidf.shape)
print('Shape test :', X_test_tfidf.shape)


Shape train: (3963, 500)
Shape test : (991, 500)


In [ ]:
# latih model Naive Bayes dan Evaluasi Performa

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

nb_model = MultinomialNB()
nb_model.fit(X_train_tfidf, y_train)

pred_nb = nb_model.predict(X_test_tfidf)

print('=== NAIVE BAYES ===')
print(f'Akurasi: {accuracy_score(y_test, pred_nb):.4f}')
print('\nClassification Report:')
print(classification_report(y_test, pred_nb))
print('\nConfusion Matrix:')
print(confusion_matrix(y_test, pred_nb))


=== NAIVE BAYES ===
Akurasi: 0.6398

Classification Report:
              precision    recall  f1-score   support

     negatif       0.66      0.66      0.66       284
      netral       0.48      0.52      0.50       310
     positif       0.77      0.72      0.74       397

    accuracy                           0.64       991
   macro avg       0.64      0.63      0.63       991
weighted avg       0.65      0.64      0.64       991


Confusion Matrix:
[[188  81  15]
 [ 77 162  71]
 [ 21  92 284]]


In [ ]:
# Latih model SVM (LinearSVC) dan Evaluasi

from sklearn.svm import LinearSVC

svm_model = LinearSVC(C=1.0, random_state=42, max_iter=2000)
svm_model.fit(X_train_tfidf, y_train)

pred_svm = svm_model.predict(X_test_tfidf)

print('=== SVM ===')
print(f'Akurasi: {accuracy_score(y_test, pred_svm):.4f}')
print('\nClassification Report:')
print(classification_report(y_test, pred_svm))
print('\nConfusion Matrix:')
print(confusion_matrix(y_test, pred_svm))

=== SVM ===
Akurasi: 0.7074

Classification Report:
              precision    recall  f1-score   support

     negatif       0.67      0.72      0.70       284
      netral       0.59      0.60      0.59       310
     positif       0.84      0.78      0.81       397

    accuracy                           0.71       991
   macro avg       0.70      0.70      0.70       991
weighted avg       0.71      0.71      0.71       991


Confusion Matrix:
[[204  62  18]
 [ 82 187  41]
 [ 17  70 310]]


In [ ]:
# Simpan model + vectorizer

import joblib

joblib.dump(svm_model, 'svm_sentiment.pkl')
joblib.dump(tfidf, 'tfidf_vectorizer.pkl')

print('Model dan vectorizer berhasil disimpan.')


Model dan vectorizer berhasil disimpan.


In [ ]:
import re
# Import Sastrawi Stemmer
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
# Import Sastrawi StopWordRemover
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

# Initialize Sastrawi Stemmer
factory_stemmer = StemmerFactory()
stemmer = factory_stemmer.create_stemmer()

# Initialize Sastrawi StopWordRemover
factory_stopword = StopWordRemoverFactory()
stopword = factory_stopword.create_stop_word_remover() # This variable 'stopword' matches the NameError

# Assuming 'kamus_normalisasi' is already defined in the global scope (kernel state confirms this)
kamus_normalisasi = {
    'ga': 'tidak',
    'gak': 'tidak',
    'gk': 'tidak',
    'nggak': 'tidak',
    'engga': 'tidak',
    'enggak': 'tidak',
    'tak': 'tidak',
    'gabisa': 'tidak bisa',
    'gakbisa': 'tidak bisa',
    'gada': 'tidak ada',
    'gaada': 'tidak ada',
    'gausah': 'tidak usah',
    'gajelas': 'tidak jelas',
    'jgn': 'jangan',
    'yg': 'yang',
    'bgt': 'banget',
    'bangett': 'banget',
    'bangeet': 'banget',
    'smpe': 'sampai',
    'smp': 'sampai',
    'kalo': 'kalau',
    'kl': 'kalau',
    'udh': 'sudah',
    'udah': 'sudah',
    'blm': 'belum',
    'tdk': 'tidak',
    'tdak': 'tidak',
    'dlu': 'dulu',
    'skrg': 'sekarang',
    'tp': 'tapi',
    'tpi': 'tapi',
    'cm': 'cuma',
    'cuman': 'cuma',
    'jg': 'juga',
    'karna': 'karena',
    'krn': 'karena',
    'klo': 'kalau',
    'kalo': 'kalau',
    'mna': 'mana',
    'membatu' : 'membantu',
    'bnyak': 'banyak',
    'bgt2': 'banget',
    'ampe': 'sampai',
    'sampe': 'sampai',
    'pake': 'pakai',
    'dipake' : 'dipakai',
    'pakaii': 'pakai',
    'pesen': 'pesan',
    'pesenan': 'pesanan',
    'pengirimn': 'pengiriman',
    'peoduk': 'produk',
    'produkny': 'produk',
    'syaa': 'saya',
    'sy': 'saya',
    'gue': 'saya',
    'gueeeee' : 'saya',
    'gua': 'saya',
    'gw': 'saya',
    'gwe': 'saya',
    'biasae': 'biasanya',
    'slalu': 'selalu',
    'allhamdulillah': 'alhamdulillah',
    'mreka': 'mereka',
    'sbgai': 'sebagai',
    'sbg': 'sebagai',
    'kmu': 'kamu',
    'org': 'orang',
    'dr': 'dari',
    'dgn': 'dengan',
    'utk': 'untuk',
    'krg': 'kurang',
    'pd': 'pada',
    'pdhl': 'padahal',
    'pdh': 'padahal',
    'krna': 'karena',
    'spt': 'seperti',
    'blanja': 'belanja',
    'blm': 'belum',
    'bln': 'bulan',
    'br': 'baru',
    'hrs': 'harus',
    'hrus': 'harus',
    'bs': 'bisa',
    'bsa': 'bisa',
    'bisaa': 'bisa',
    'bgt': 'banget',
    'bgtt': 'banget',
    'lg': 'lagi',
    'lgi': 'lagi',
    'aja': 'saja',
    'doang': 'saja',
    'kali2': 'kali kali',
    'wkwkw': '',
    'wkwk': '',
    'wk': '',
    'yaa': '',
    'yah': '',
    'nih': '',
    'sih': '',
    'dong': '',
    'deh': '',
    'kok': '',
    'lah': '',
    'pun': '',
    'ny': 'nya',
    'apk': 'aplikasi',
    'apl': 'aplikasi',
    'app': 'aplikasi',
    'hp': 'handphone',
    'telp': 'telepon',
    'notelp': 'nomor telepon',
    'wa': 'whatsapp',
    'cs': 'customer service',
    'sop': 'prosedur',
    'respon': 'respons',
    'scra': 'secara',
    'ak': 'akan',
    'akn': 'akan',
    'msk': 'masuk',
    'maks': 'maksimal',
    'kmrn': 'kemarin',
    'tgl': 'tanggal',
    'jwbnnya': 'jawabannya',
    'ttp': 'tetap',
    'sdh': 'sudah'
}

def preprocess_full(text):
    # Case folding
    text = text.lower()

    # Remove non-alphanumeric characters (keep only letters and spaces)
    text = re.sub(r'[^a-z\s]', '', text)

    # Tokenization
    tokens = text.split()

    # Normalization (using the global 'kamus_normalisasi')
    normalized_tokens = [kamus_normalisasi.get(token, token) for token in tokens]
    text = ' '.join(normalized_tokens) # Join back for Sastrawi StopWordRemover

    # Stopword removal
    text = stopword.remove(text) # This line now uses the 'stopword' object

    # Stemming
    tokens_after_stopword = text.split()
    stemmed_tokens = [stemmer.stem(word) for word in tokens_after_stopword]

    # Join back into a string
    text = ' '.join(stemmed_tokens)

    return text

review_baru = [
    "Produk yang diterima lengkap dan pengiriman sesuai estimasi",
    "Kecewa banget, barang yang diterima rusak",
    "Kecewa sih karena voucher tidak bisa digunakan"
]

review_clean = [preprocess_full(r) for r in review_baru]
review_vec   = tfidf.transform(review_clean)

print('Prediksi Naive Bayes:', nb_model.predict(review_vec))
print('Prediksi SVM        :', svm_model.predict(review_vec))

Prediksi Naive Bayes: ['positif' 'negatif' 'negatif']
Prediksi SVM        : ['positif' 'negatif' 'negatif']


In [ ]:
import numpy
import sklearn
import joblib

print('NumPy     :', numpy.__version__)
print('Scikit-learn:', sklearn.__version__)
print('Joblib    :', joblib.__version__)

NumPy     : 2.1.3
Scikit-learn: 1.6.1
Joblib    : 1.5.3
